# Basic Configuration
version: 1.0
name: project-estimation-copilot
description: AI-powered project estimation system

# System Settings
settings:
  language: en
  model: gpt-4
  temperature: 0.7
  max_tokens: 2000
  save_estimates: true
  output_format: markdown

# Issue Template Configuration
issue_template:
  name: Project Estimation Request
  description: Request a new project estimation
  title_prefix: "[Estimation]"
  labels:
    - estimation
    - project-planning

  # Form Fields
  fields:
    project_name:
      type: input
      label: Project Name
      required: true
      placeholder: e.g., E-commerce Platform

    tech_stack:
      type: textarea
      label: Tech Stack
      required: true
      placeholder: |
        - Frontend: React.js
        - Backend: Node.js
        - Database: MongoDB

    features:
      type: textarea
      label: Features
      required: true
      placeholder: |
        1. User Authentication
        2. Product Management
        3. Shopping Cart

    team_size:
      type: input
      label: Team Size
      required: true
      placeholder: "e.g., 4"

    experience_level:
      type: dropdown
      label: Team Experience Level
      required: true
      options:
        - Junior Team (0-2 years)
        - Mid-Level Team (2-5 years)
        - Senior Team (5+ years)
        - Mixed Experience Levels

# Estimation Template
estimation_template:
  sections:
    - title: Project Details
      fields:
        - project_name
        - tech_stack
        - team_size
        - experience_level

    - title: Timeline Breakdown
      fields:
        - planning_duration
        - development_duration
        - testing_duration
        - buffer_duration
        - total_duration

    - title: Risk Assessment
      fields:
        - technical_risks
        - resource_risks
        - timeline_risks

    - title: Confidence Level
      fields:
        - rating
        - factors

    - title: Assumptions
      fields:
        - assumptions_list
        - dependencies

# Historical Data Structure
historical_data:
  projects:
    - category: E-commerce
      examples:
        - project_id: EC001
          project_name: Online Fashion Store
          tech_stack:
            frontend: ["React", "Redux", "Tailwind CSS"]
            backend: ["Node.js", "Express"]
            database: "MongoDB"
            additional: ["AWS S3", "Stripe"]
          team_size: 4
          experience_level: "Mixed"
          features:
            - name: "User Authentication"
              complexity: "Medium"
              actual_time: "2 weeks"
              resources_required: 2
            - name: "Product Catalog"
              complexity: "High"
              actual_time: "4 weeks"
              resources_required: 3
          actual_duration: "16 weeks"
          initial_estimate: "14 weeks"
          variance: "+2 weeks"

    - category: CRM
      examples:
        - project_id: CRM001
          project_name: Sales Pipeline Manager
          tech_stack:
            frontend: ["Vue.js", "Vuex"]
            backend: ["Python", "Django"]
            database: "PostgreSQL"
          team_size: 5
          experience_level: "Senior"
          features:
            - name: "Lead Management"
              complexity: "High"
              actual_time: "3 weeks"
              resources_required: 3

# Complexity Multipliers
complexity_multipliers:
  team_experience:
    junior: 1.5
    mid_level: 1.2
    senior: 1.0
    mixed: 1.3

  feature_complexity:
    low: 1.0
    medium: 1.5
    high: 2.0

  tech_stack_familiarity:
    new: 1.4
    familiar: 1.0
    mixed: 1.2

# Time Allocations
time_allocations:
  project_phases:
    planning:
      percentage: 10
      minimum_weeks: 1
    development:
      percentage: 60
      buffer: 0.2
    testing:
      percentage: 20
      minimum_weeks: 2
    deployment:
      percentage: 10
      minimum_weeks: 1

  feature_types:
    authentication:
      base_time: "2 weeks"
      complexity_factor: 1.2
    data_integration:
      base_time: "3 weeks"
      complexity_factor: 1.5
    user_interface:
      base_time: "2 weeks"
      complexity_factor: 1.3

# Commands Configuration
commands:
  estimate:
    command: /estimate
    description: Generate project estimation
    usage: /estimate [project-name]
    required_fields:
      - project_name
      - tech_stack
      - features

  update_template:
    command: /update-template
    description: Update estimation template
    usage: /update-template [template-name]

  view_history:
    command: /view-history
    description: View estimation history
    usage: /view-history [project-name]

# Output Configuration
output:
  format: markdown
  save_path: ./estimations
  include_timestamp: true
  version_control: true
  notification:
    enabled: true
    channels:
      - github_issues
      - email

# Validation Rules
validation:
  required_fields:
    - project_name
    - tech_stack
    - features
    - team_size
    - experience_level

  constraints:
    team_size:
      min: 1
      max: 20
    duration_weeks:
      min: 1
      max: 52

# Error Messages
error_messages:
  missing_field: "Required field {field} is missing"
  invalid_input: "Invalid input for {field}"
  estimation_failed: "Failed to generate estimation"